---
  config:
    layout: elk
    theme: neutral
    class:
      hideEmptyMembersBox: true
---

stateDiagram-v2
    state Operating {
        [*] --> Automatic
        Manual : Manual
        Manual : dbs door value / send door value do wcs
        Manual : wcs door value / send door value do dbs
        Automatic --> Manual : wcs state MANUAL || dbs btn pressed
        Manual --> Automatic : wcs state AUTOMATIC || dbs btn pressed

        state Automatic {
            Safe : Safe
            Safe : entry / send door = 0% to dbs and wcs

            Danger : Danger
            Danger : entry / send door = 50% to dbs and wcs

            Critical : Critical
            Critical : entry / send door = 100% to dbs and wcs

            CheckDanger : Check danger
            CheckDanger : entry / timer = T1
            CheckDanger : exit / delete timer

            [*] --> Safe
            Safe --> CheckDanger : waterLevel >= L1
            CheckDanger --> Danger : timer ended
            CheckDanger --> Critical : waterLevel >= L2
            CheckDanger --> Safe : waterLevel < L1
            Danger --> Critical : waterLevel >= L2
            Danger --> Safe : waterLevel < L1
            Critical --> Danger : waterLevel < L2
        }
    }
    Operating --> Operating : MQTT value / send to dbs and wcs

    Unconnected : Unconnected
    Unconnected : entry / send state UNCONNECTED to wcs and dbs

    [*] --> Operating
    Operating --> Unconnected : MQTT value timeout
    Unconnected --> Operating : new MQTT value / return to previous state AUTOMATIC/MANUAL
