@startuml
hide empty description

state start <<start>>

state Online
Online : entry / turn green led on
Online : entry / turn red led off
Online : entry / connect MQTT client
Online : do / sonar sampling


state Offline
Offline : entry / turn green led off
Offline : entry / turn red led on
Offline : entry / stop sonar sampling

start --> Offline

Offline --> Online : wifi connected
Online --> Offline : wifi disconnected

@enduml
