@startuml
hide empty description

state Unconnected
state Operating {
    state Automatic
    state Manual
    [*] --> Automatic

    Automatic --> Manual : serial [STATE:MANUAL] || button pressed
    Manual --> Automatic : serial [STATE:AUTOMATIC] || button pressed

    Manual --> Manual : pot value changed / set servo angle
}

[*] --> Operating

Operating --> Operating : serial [DOOR:<value>] / set servo angle
Operating --> Unconnected : serial [STATE:UNCONNECTED]
Unconnected --> Manual : serial [STATE:MANUAL]
Unconnected --> Automatic : serial [STATE:AUTOMATIC]

@enduml
