@startuml AlarmTask
hide empty description

title "Alarm task"

state start <<start>>

state "Idle" as idle
idle : entry / alarm led off

state "Blocked" as blocked

state "Prealarm temperature reading" as prealarmTempReading

state "Prealarm temperature monitoring" as prealarmTempMonitoring
prealarmTempMonitoring : entry / timer = PREALARM_TIME

state "Wait operations" as waitOperations

state "Alarm temperature reading" as alarmTempReading

state "Alarm temperature monitoring" as alarmTempMonitoring
alarmTempMonitoring : entry / timer = ALARM_TIME

start -d-> idle

idle -r-> blocked : state == Alarm
blocked -l-> idle : state != Alarm

idle -d-> prealarmTempReading : state == Inside || Takeoff || Landing

prealarmTempReading -d-> prealarmTempMonitoring : temp >= PREALARM_TEMP
prealarmTempReading -u-> idle : state != Inside || Takeoff || Landing
prealarmTempMonitoring -u-> prealarmTempReading : temp < PREALARM_TEMP
prealarmTempMonitoring -r-> waitOperations : timer ended

waitOperations -r-> alarmTempReading : state != Takeoff || Landing / prevState = state, state = Prealarm

alarmTempReading -d-> alarmTempMonitoring : temp >= ALARM_TEMP
alarmTempReading -l-> prealarmTempReading : temp <= PREALARM_TEMP / state = prevState
alarmTempMonitoring -u-> alarmTempReading : temp < ALARM_TEMP
alarmTempMonitoring -u-> blocked : timer ended / state = Alarm, alarm led on

@enduml
