@startuml AlarmTask
!pragma layout elk
hide empty description

title "Alarm task"

state start <<start>>

state "Idle" as idle
idle : entry / alarm led off

state "Blocked" as blocked

state "Prealarm monitoring" as prealarm {
    state startPrealarm <<start>>

    state "Temperature reading" as prealarmTempReading

    state "Temperature monitoring" as prealarmTempMonitoring
    prealarmTempMonitoring : entry / timer = PREALARM_TIME

    state endPrealarm <<end>>
}

state "Wait operations" as waitOperations

state "Alarm monitoring" as alarm {
    state startAlarm <<start>>

    state "Temperature reading" as alarmTempReading

    state "Temperature monitoring" as alarmTempMonitoring
    alarmTempMonitoring : entry / timer = ALARM_TIME

    state endAlarm <<end>>
}

start -d-> idle
idle -r-> blocked : state == Alarm
blocked -l-> idle : state != Alarm
idle -d-> prealarm : state == Inside || Takeoff || Landing

startPrealarm -r-> prealarmTempReading
prealarmTempReading -r-> prealarmTempMonitoring : temp >= PREALARM_TEMP
prealarmTempReading -u-> idle : state != Inside || Takeoff || Landing
prealarmTempMonitoring -l-> prealarmTempReading : temp < PREALARM_TEMP
prealarmTempMonitoring -r-> endPrealarm : timer ended

prealarm -d-> waitOperations

waitOperations -d-> alarm : state != Takeoff || Landing

startAlarm -u-> alarmTempReading
alarmTempReading -r-> alarmTempMonitoring : temp >= ALARM_TEMP
alarmTempReading -u-> prealarm : temp <= PREALARM_TEMP
alarmTempMonitoring -l-> alarmTempReading : temp < ALARM_TEMP
alarmTempMonitoring -r-> endAlarm : timer ended

@enduml
