@startuml BlinkTask
hide empty description

title "Blink task"

state start <<start>>

state "Idle" as idle
idle : entry / blink led off

state "Blocked" as blocked

state "On" as on
on : entry / blink led on
on : entry / timer = BLINK_PERIOD

state "Off" as off
off : entry / blink led off
off : entry / timer = BLINK_PERIOD

start -d-> idle

idle -l-> blocked : state == Alarm
blocked -r-> idle : state != Alarm

idle -r-> on : state == Takeoff || Landing

on -d-> off : timer ended
off -u-> on : timer ended

on -l-> idle : state != Takeoff && Landing
off -l-> idle : state != Takeoff && Landing

@enduml
