@startuml DoorTask
hide empty description

title "Door task"

state start <<start>>

state "Closed" as closed
closed : entry / servo = DOOR_CLOSED_ANGLE

state "Blocked" as blocked

state "Open" as open
open : entry / servo = DOOR_OPEN_ANGLE

start -r-> closed

closed -u-> blocked : state == Alarm
blocked -d-> closed : state != Alarm
closed -d-> open : message available [REQUEST_TAKEOFF] / state = Takeoff
closed -u-> open : state == Takeoff || Landing

open -l-> closed : state != Takeoff || Landing

@enduml
