@startuml DPDTask
!pragma layout smetana
hide empty description

title "DPD task"

state start <<start>>

state "Idle" as idle

state "Blocked" as blocked

state "Reading" as reading
reading : entry / timer = REQUEST_LANDING_TIMEOUT

start -r-> idle

idle -u-> blocked : state == Alarm
blocked -d-> idle : state != Alarm

idle -d-> reading : message available [REQUEST_LANDING] && state == Outside

reading -u-> idle : drone present / state = Landing
reading -u-> idle : timer ended / state = Outside

@enduml
