@startuml ResetTask
!pragma layout smetana
hide empty description

title "Reset task"

state start <<start>>

state "Idle" as idle

state "Wait reset" as waitReset

start -d-> idle

idle -r-> idle : state != Prealarm && Alarm / prevState = state
idle -d-> waitReset : state == Alarm

waitReset -u-> idle : button pressed / state = prevState

@enduml
