@startuml StateChangeTask
!pragma layout smetana
hide empty description

state start <<start>>

state "Print" as print
print : entry / display state
print : entry / send state
print : entry / prevState = state

state "Idle" as idle

start -d-> print

print -d-> idle
print -[hidden]d-> idle
idle -u-> print : state != prevState

@enduml
